import type { Metadata } from "next";
import "./globals.css";
import { sans_serif } from "./fonts";
import Navbar from "./components/navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./components/landing-page/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans_serif.className}  antialiased`}>
        {modal}
        <Toaster />
        <nav>
          <Navbar />
        </nav>{" "}
        {children}
        <Footer />
      </body>
    </html>
  );
}
